#!/bin/bash

set -eux # Verbose logging to juju debug-log
juju-log "Installing mono via apt-get"
apt-get -y install mono-complete

#make a temporary directory to house the TShock and Terraria server bins
juju-log "Creating a temporary cache for setup"

#Force removal of the directory if it exists
rm -rf /tmp/terraria
mkdir /tmp/terraria


#create the cache
cd /tmp/terraria

juju-log "fetching the 3.8.0 copy of the TShock server" 
wget -O tshock.zip https://github.com/downloads/TShock/TShock/TShock%203.8.0.0304.zip

unzip /tmp/terraria/tshock.zip

#cleanup the download
rm tshock.zip

#move the server bins to its final resting place
mv /tmp/terraria/terraria /opt/terraria
